// AUTO-GENERATED by `npm run refresh:snapshots`. Do not edit by hand.
// Stub: run `FACTORY_API_KEY=... npm run refresh:snapshots` to populate.
// Until then, catalog.ts falls back to the hand-maintained FALLBACK_ROWS.

import type { AvailableModelConfig } from "@factory/droid-sdk";

export const SNAPSHOT_TAKEN_AT: string | null = null;
export const SNAPSHOT_KEY: string | null = null;

export const SNAPSHOT_MODELS: readonly AvailableModelConfig[] = [];
